ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :edit]

end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord

  validates :birth_date, presence: true
  validates :color, presence: true
  validates :name, presence: true
  validates :sex, presence: true
  validates :description, presence: true

  def self.age(birth_date)
    ((Time.now.to_date - birth_date)/365.25).round(1)
  end
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end
 
  # work on the model, create a couple cat seeds
  # create age method to figure out the sure

end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/index.html.erb
<h1>All the cats!</h1>

<ul>

    <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat.id)%>"><%=cat.name %> </a></li>
    <% end %>

</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<h1>Add a cat to rent!</h1>

<form action="<%= cats_url %>" method="post">

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= @cat.name %>">
  <br>

  <label for="birth_date">Birth Date</label>
  <input id="birth_date" type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br>

  <label>Sex</label>
  <input id="M" type="radio" name="cat[sex]" value="M" <%= @cat.sex == 'M' ? "": 'checked' %>>
  <label for="M">M</label>
  <%# <br> %>
  <input id="F" type="radio" name="cat[sex]" value="F"<%= @cat.sex == 'F' ? "": 'checked' %>>
  <label for="F">F</label>
  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <% @cat.color.nil? ? "" : "selected" %>>--- Please select a color ---</option>
    <option value="White" <% @cat.color == "White" ? "selected" : "" %>>White</option>
    <option value="Calico" <% @cat.color == "Calico" ? "selected" : "" %>>Calico</option>
    <option value="Black" <% @cat.color == "Black" ? "selected" : "" %>>Black</option>
    <option value="Orange" <% @cat.color == "Orange" ? "selected" : "" %>>Orange</option>

  </select>
  <br>

  <label for="description">Description</label>
  <textarea name="cat[description]">
  <%= @cat.description %>
  </textarea>
  <br>

  <input type="submit" value="Add Cat!">

</form>

ninety_nine_cats/app/views/cats/show.html.erb
<h1>Show cat!</h1>

<table>
    <thead>
        <tr>
            <th>Cat's name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Name</td>
            <td><%= @cat.name %></td>
        </tr>
        <tr>
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr>
            <td>Sex</td>
            <td><%= @cat.sex %></td>
        </tr>
        <tr>
            <td>Birth day</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr>
            <td>Description</td>
            <td><%= @cat.description %></td>
        </tr>
    </tbody>
</table>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyProjectName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>